"""Generators for geometric graphs.
"""

import math
from bisect import bisect_left
from itertools import combinations, product
import numpy as np
import scipy as sp
import networkx as nx
from networkx.utils import py_random_state

import coordinate

__all__ = [
    "waxman_graph",
    "waxman_variable",
    "soft_random_geometric_graph",
]


def combinations_to_run(*args):
    """ Simple method to make an array of all possible combinations of given
    args. Usefull for consecutive runs or parallell simulations. Each element
    must contain the same type for the same parameter (no nested ragged lists 
    etc.).

    Parameters
    ----------
    *args : float or 1-d array
        Arguments to meshgrid.
    seed : seed
        Returns streams for runs at last element, such that each has an
        independent stream.
    Returns
    -------
    grid : ndarray
        Array containing all possible combinations of input variables.
    """
    grid = np.array(np.meshgrid(*args, indexing='ij'),
                    dtype=object).T.reshape(-1, len(args))
    grid = list(map(tuple, grid))

    return grid


def waxman_graph_mod(
    n, pos=None, beta=0.6, alpha=0.2, L=None, domain=(0, 0, 1, 1), p_dist=None,
    periodic=False, seed=None
):
    r"""Returns a modified Waxman random graph.

    The Waxman random graph model places `n` nodes uniformly at random
    in a rectangular domain. Each pair of nodes at distance `d` is
    joined by an edge with probability. Here we adjust the placement to 
    incorporate multiple allowed conformations of node placements. If no 
    positions are passed, a uniform placement is used.

    .. math::
            p = \beta \exp(-d / \alpha L).

    This function implements both Waxman models, using the `L` keyword
    argument.

    * Waxman-1: if `L` is not specified, it is set to be the maximum distance
      between any pair of nodes.
    * Waxman-2: if `L` is specified, the distance between a pair of nodes is
      chosen uniformly at random from the interval `[0, L]`.

    Parameters
    ----------
    n : int or iterable
        Number of nodes or iterable of nodes
    pos : dict, optional
        A dictionary keyed by node with node positions as values.
    beta: float
        Model parameter

    alpha: float
        Model parameter
    L : float, optional
        Maximum distance between nodes.  If not specified, the actual distance
        is calculated.
    domain : four-tuple of numbers, optional
        Domain size, given as a tuple of the form `(x_min, y_min, x_max,
        y_max)`.
    periodic : bool
        Choose to use a periodic boundary or not for distance measure
    metric : function
        A metric on vectors of numbers (represented as lists or
        tuples). This must be a function that accepts two lists (or
        tuples) as input and yields a number as output. The function
        must also satisfy the four requirements of a `metric`_.
        Specifically, if $d$ is the function and $x$, $y$,
        and $z$ are vectors in the graph, then $d$ must satisfy

        1. $d(x, y) \ge 0$,
        2. $d(x, y) = 0$ if and only if $x = y$,
        3. $d(x, y) = d(y, x)$,
        4. $d(x, z) \le d(x, y) + d(y, z)$.

        If this argument is not specified, the Euclidean distance metric is
        used.

        .. _metric: https://en.wikipedia.org/wiki/Metric_%28mathematics%29

    seed : integer, random_state, or None (default)
        Indicator of random number generation state.
        See :ref:`Randomness<randomness>`.

    Returns
    -------
    Graph
        A random Waxman graph, undirected and without self-loops. Each
        node has a node attribute ``'pos'`` that stores the position of
        that node in Euclidean space as generated by this function.

    Examples
    --------
    Specify an alternate distance metric using the ``metric`` keyword
    argument. For example, to use the "`taxicab metric`_" instead of the
    default `Euclidean metric`_::

        >>> dist = lambda x, y: sum(abs(a - b) for a, b in zip(x, y))
        >>> G = nx.waxman_graph(10, 0.5, 0.1, metric=dist)

    .. _taxicab metric: https://en.wikipedia.org/wiki/Taxicab_geometry
    .. _Euclidean metric: https://en.wikipedia.org/wiki/Euclidean_distance

    Notes
    -----
    Starting in NetworkX 2.0 the parameters alpha and beta align with their
    usual roles in the probability distribution. In earlier versions their
    positions in the expression were reversed. Their position in the calling
    sequence reversed as well to minimize backward incompatibility.

    References
    ----------
    .. [1]  B. M. Waxman, *Routing of multipoint connections*.
       IEEE J. Select. Areas Commun. 6(9),(1988) 1617--1622.
    """
    
    G = nx.empty_graph(n, create_using=nx.Graph)
    dmin, dmax = np.array_split(domain, 2)

    if pos is None:
        pos = {v: seed.uniform(dmin, dmax) for v in G}

    nx.set_node_attributes(G, pos, "pos")

    dists = coordinate.periodic_dist(np.asarray(
        [*pos.values()]), domain=domain, periodic=periodic)

    if L is None:
        L = np.amax(dists)

    if p_dist is None:

        def p_dist(dist, L=L, beta=.6, alpha=.2):
            return beta * math.exp(-dist / (alpha * L)) 

    def should_join(edge, dists=dists, L=L,  beta=beta, alpha=alpha):
        u, v = edge
        dist = dists[u, v]
        return seed.random() < p_dist(dist, L=L,  beta=beta, alpha=alpha)

    G.add_edges_from(filter(should_join, combinations(G, 2)))
    return G


def waxman_digraph_mod(
    n, pos=None, L=None, beta=0.6, alpha=0.2, domain=(0, 0, 1, 1), p_dist=None,
    periodic=False, seed=None

):
    r"""Returns a modified Waxman random graph.

    The Waxman random graph model places `n` nodes uniformly at random
    in a rectangular domain. Each pair of nodes at distance `d` is
    joined by an edge with probability. Here we adjust the placement to 
    incorporate multiple allowed conformations of node placements. If no 
    positions are passed, a uniform placement is used.

    .. math::
            p = \beta \exp(-d / \alpha L).

    This function implements both Waxman models, using the `L` keyword
    argument.

    * Waxman-1: if `L` is not specified, it is set to be the maximum distance
      between any pair of nodes.
    * Waxman-2: if `L` is specified, the distance between a pair of nodes is
      chosen uniformly at random from the interval `[0, L]`.

    Parameters
    ----------
    n : int or iterable
        Number of nodes or iterable of nodes
    pos : dict, optional
        A dictionary keyed by node with node positions as values.
    beta: float
        Model parameter
    alpha: float
        Model parameter
    L : float, optional
        Maximum distance between nodes.  If not specified, the actual distance
        is calculated.
    domain : four-tuple of numbers, optional
        Domain size, given as a tuple of the form `(x_min, y_min, x_max,
        y_max)`.
    periodic : bool
        Choose to use a periodic boundary or not for distance measure
    metric : function
        A metric on vectors of numbers (represented as lists or
        tuples). This must be a function that accepts two lists (or
        tuples) as input and yields a number as output. The function
        must also satisfy the four requirements of a `metric`_.
        Specifically, if $d$ is the function and $x$, $y$,
        and $z$ are vectors in the graph, then $d$ must satisfy

        1. $d(x, y) \ge 0$,
        2. $d(x, y) = 0$ if and only if $x = y$,
        3. $d(x, y) = d(y, x)$,
        4. $d(x, z) \le d(x, y) + d(y, z)$.

        If this argument is not specified, the Euclidean distance metric is
        used.

        .. _metric: https://en.wikipedia.org/wiki/Metric_%28mathematics%29

    seed : integer, random_state, or None (default)
        Indicator of random number generation state.
        See :ref:`Randomness<randomness>`.

    Returns
    -------
    Graph
        A random Waxman graph, undirected and without self-loops. Each
        node has a node attribute ``'pos'`` that stores the position of
        that node in Euclidean space as generated by this function.

    Examples
    --------
    Specify an alternate distance metric using the ``metric`` keyword
    argument. For example, to use the "`taxicab metric`_" instead of the
    default `Euclidean metric`_::

        >>> dist = lambda x, y: sum(abs(a - b) for a, b in zip(x, y))
        >>> G = nx.waxman_graph(10, 0.5, 0.1, metric=dist)

    .. _taxicab metric: https://en.wikipedia.org/wiki/Taxicab_geometry
    .. _Euclidean metric: https://en.wikipedia.org/wiki/Euclidean_distance

    Notes
    -----
    Starting in NetworkX 2.0 the parameters alpha and beta align with their
    usual roles in the probability distribution. In earlier versions their
    positions in the expression were reversed. Their position in the calling
    sequence reversed as well to minimize backward incompatibility.

    References
    ----------
    .. [1]  B. M. Waxman, *Routing of multipoint connections*.
       IEEE J. Select. Areas Commun. 6(9),(1988) 1617--1622.
    """

    G = nx.empty_graph(n, create_using=nx.DiGraph)
    dmin, dmax = np.array_split(domain, 2)

    if pos is None:
        pos = {v: seed.uniform(dmin, dmax) for v in G}

    nx.set_node_attributes(G, pos, "pos")

    dists = coordinate.periodic_dist(np.asarray(
        [*pos.values()]), domain=domain, periodic=periodic)

    if L is None:
        L = np.amax(dists)

    if p_dist is None:

        def p_dist(dist, L, beta=0.4, alpha=0.1):
            return beta * math.exp(-dist / (alpha * L))

    def should_join(edge, dists=dists, L=L, beta=beta, alpha=alpha):
        u, v = edge
        if u == v:
            return False
        dist = dists[u, v]
        return seed.random() < p_dist(dist, L, beta=beta, alpha=alpha)

    G.add_edges_from(filter(should_join, product(G, G)))
    return G
